---
openapi: 3.0.3
info:
  title: Pizza Order Api
  version: "1.0"
paths:
  /pizza/orders:
    post:
      tags:
        - "Pizza Order Api"
      summary: Create a new order
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        description: Pizza order content
        required: true
        content:
          application/json:
            schema:
              type: array
              maxItems: 16
              items:
                $ref: '#/components/schemas/PizzaOrderDto'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaOrderCreatedDto'
        "400":
          description: Bad request
        "403":
          description: Forbidden
        "500":
          description: Internal server error
components:
  schemas:
    PizzaOrderDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the pizza being ordered.
          example: "Margherita Pizza"
        quantity:
          type: integer
          description: Number of pizza being ordered.
          example: 3
          minimum: 1
    PizzaOrderCreatedDto:
      type: object
      properties:
        orderId:
          type: string
          description: Order unique id
          format: uuid
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      description: JWT Authorizing token to allow access to endpoint